<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Report" duration-ms="4769" started-at="2019-10-31T11:49:53 ALMT" finished-at="2019-10-31T11:49:58 ALMT">
    <groups>
    </groups>
    <test name="Healthcheck Report" duration-ms="4769" started-at="2019-10-31T11:49:53 ALMT" finished-at="2019-10-31T11:49:58 ALMT">
      <class name="Extentreports.Extentreportdemo.Healthcheck">
        <test-method status="FAIL" signature="print()[pri:0, instance:Extentreports.Extentreportdemo.Healthcheck@7b49cea0]" name="print" duration-ms="27" started-at="2019-10-31T11:49:54 ALMT" finished-at="2019-10-31T11:49:54 ALMT">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [10] but found [5]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [10] but found [5]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:839)
at org.testng.Assert.assertEquals(Assert.java:849)
at Extentreports.Extentreportdemo.Healthcheck.print(Healthcheck.java:32)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- print -->
        <test-method status="PASS" signature="print1()[pri:0, instance:Extentreports.Extentreportdemo.Healthcheck@7b49cea0]" name="print1" duration-ms="1" started-at="2019-10-31T11:49:54 ALMT" finished-at="2019-10-31T11:49:54 ALMT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- print1 -->
        <test-method status="PASS" signature="website()[pri:0, instance:Extentreports.Extentreportdemo.Healthcheck@7b49cea0]" name="website" duration-ms="4353" started-at="2019-10-31T11:49:54 ALMT" finished-at="2019-10-31T11:49:58 ALMT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- website -->
      </class> <!-- Extentreports.Extentreportdemo.Healthcheck -->
    </test> <!-- Healthcheck Report -->
  </suite> <!-- Report -->
</testng-results>
