<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Gulnoza-PC" ignored="0" name="Healthcheck Report" tests="3" failures="1" timestamp="2019-10-31T11:49:58 ALMT" time="4.769" errors="0">
  <testcase name="print" time="0.027" classname="Extentreports.Extentreportdemo.Healthcheck">
    <failure type="java.lang.AssertionError" message="expected [10] but found [5]">
      <![CDATA[java.lang.AssertionError: expected [10] but found [5]
at Extentreports.Extentreportdemo.Healthcheck.print(Healthcheck.java:32)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- print -->
  <testcase name="print1" time="0.001" classname="Extentreports.Extentreportdemo.Healthcheck"/>
  <testcase name="website" time="4.353" classname="Extentreports.Extentreportdemo.Healthcheck"/>
</testsuite> <!-- Healthcheck Report -->
